# Generated by Django 4.2.7 on 2023-11-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='label',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=1),
        ),
    ]
